### ISSUE TITLE
rollback hasMany relationships

### ISSUE THREAD

**Issue by cwarny** [dylanmensaert/ember-rollback-relationships#5]
Any plan to support rollback of hasMany relationships as well? Or some pointers for how one could go about supporting that?

**Comment by cwarny** [comment]
This is my current workaround. In the model file, I add the following two functions:

	pinRelationships() {
		let items = this.get('items').mapBy('id');
		let pinnedRelationships = {
			items: items
		};

		this.set('_pinnedRelationships', pinnedRelationships);
	},

	rollbackRelationships() {
		let items = this.get('_pinnedRelationships.items');
		this.set('items', items.map(item => this.store.peekRecord('item', item)));
	}

I call `pinRelationships` in the route's `afterModel` hook and `rollbackRelationships` in the controller in the function in the actions hash that is called when undoing changes.

Workaround inspired by this thread: https://discuss.emberjs.com/t/rollback-has-many-relationship-data/13177

**Comment by dylanmensaert** [comment]
Functionality available in [v1.2.2](https://github.com/dylanmensaert/ember-rollback-relationships/releases/tag/1.2.2)

Closing
