### ISSUE TITLE
Cannot read property 'eachRelationship' of undefined

### ISSUE THREAD

**Issue by krypton9208** [dylanmensaert/ember-rollback-relationships#6]
I have a problem with some models when I entering to route with organizations...

model organization:

> export default DS.Model.extend({
>   name: DS.attr('string'),
>   tax_id: DS.attr('string'),
>   owner: DS.belongsTo('user', {
>     inverse: 'organization'
>   }),
>   updated_at: DS.attr('isodate'),
>   created_at: DS.attr('isodate'),
>   address: DS.belongsTo('address'),
>   bank_account_number: DS.attr('string'),
>   user_ids: DS.hasMany('user', {
>     inverse: 'organizations'
>   }),
>   application_id: DS.belongsTo('application'),
>   carriers: DS.hasMany('carrier'),
>   services: DS.hasMany('service'),
>   trucker_id: DS.attr('string', { defaultValue: config.APP.TRUCKER_ID}),
>   invoice_address: DS.belongsTo('invoice'),
>   contact_person: DS.belongsTo('contact'),
>   virtual: DS.attr('boolean')
> });

address model:

> export default DS.Model.extend({
>   line1: DS.attr('string'),
>   line2: DS.attr('string'),
>   city: DS.attr('string'),
>   building_number: DS.attr('string'),
>   street: DS.attr('string'),
>   post_code: DS.attr('string'),
>   country_code: DS.attr('string', {
>     defaultValue() { return 'PL'; }
>   }),
> });

![image](https://user-images.githubusercontent.com/6137589/38794377-2f34f170-4155-11e8-998f-42e11ea1c3c4.png)

![image](https://user-images.githubusercontent.com/6137589/38794326-00a27ae4-4155-11e8-9549-81156d6592ab.png)

**Comment by dylanmensaert** [comment]
`address: DS.belongsTo(),` does not point to the address model.
Should be: `address: DS.belongsTo('address'),`?

Let me know if this works.

**Comment by krypton9208** [comment]
Yes. I change it for test, and i forget to restore before publishing issue

pon., 16 kwi 2018, 13:56 użytkownik Dylan Mensaert <notifications@github.com>
napisał:

**Comment by dylanmensaert** [comment]
So everything works now?

**Comment by krypton9208** [comment]
No. Nothing happen when i restore to  DS.belongsTo('address')

**Comment by dylanmensaert** [comment]
I am pushing a potential fix right now.

Hang tight :)

**Comment by dylanmensaert** [comment]
Could you try with [v1.2.2](https://github.com/dylanmensaert/ember-rollback-relationships/releases)?

**Comment by krypton9208** [comment]
Yes, now it's working. But. i have other error when i try to call rollbackRelationships(); Create new issue?

**Comment by dylanmensaert** [comment]
Yes please! I will close this one
