### ISSUE TITLE
Cannot read property 'user_ids' of undefined

### ISSUE THREAD

**Issue by krypton9208** [dylanmensaert/ember-rollback-relationships#7]
I have this error when i call organization.rollbackRelationships();

![image](https://user-images.githubusercontent.com/6137589/38809615-66395f7e-4184-11e8-9334-b01926cb46d7.png)

![screenshot from 2018-04-16 14-36-35](https://user-images.githubusercontent.com/6137589/38809623-6fd84d92-4184-11e8-94e3-f2b9fa66eb31.png)
![screenshot from 2018-04-16 14-36-44](https://user-images.githubusercontent.com/6137589/38809624-6ffa8a38-4184-11e8-82b2-078ebb2353f6.png)
![image](https://user-images.githubusercontent.com/6137589/38809848-3d7d0be8-4185-11e8-92ef-28db0687f023.png)

organization model (part):
![image](https://user-images.githubusercontent.com/6137589/38809646-852729f2-4184-11e8-9534-efebbee502dd.png)
user model (part):
![image](https://user-images.githubusercontent.com/6137589/38809661-9507478a-4184-11e8-9848-3b91f61ec5ca.png)

**Comment by dylanmensaert** [comment]
Many-to-many is currently not supported.

Is your hasMany embedded?

**Comment by krypton9208** [comment]
I have hasMany.
webhook:
![image](https://user-images.githubusercontent.com/6137589/38810467-268f5e34-4187-11e8-9084-4d13f0d6ff4b.png)

webhookevent:
![image](https://user-images.githubusercontent.com/6137589/38810473-2fef4692-4187-11e8-8f1f-cfc8816d18bc.png)

for name: "events"
![image](https://user-images.githubusercontent.com/6137589/38810540-5327b874-4187-11e8-8e0a-4e7c353e1edc.png)

![image](https://user-images.githubusercontent.com/6137589/38810487-3ab04626-4187-11e8-877c-2d9221b1aeb1.png)

**Comment by dylanmensaert** [comment]
`event: DS.attr('string')` should be `event: DS.belongsTo('webhook')`

**Comment by krypton9208** [comment]
ok, now no errors occured. But steel is problem with rellback changes.
before edit:
![image](https://user-images.githubusercontent.com/6137589/38811159-2d0e9c32-4189-11e8-8088-360b3c35bd11.png)

after i remove only 2 events nothing else and click cancel:
![image](https://user-images.githubusercontent.com/6137589/38811218-45a96876-4189-11e8-877a-8d4137a02532.png)

looks like 'application: DS.belongsTo('application')'  was cleared on webhook.rollbackRelationships();

**Comment by dylanmensaert** [comment]
Yes, `webhook.rollbackRelationships()` performs a rollback for **all** relationships, so also `application`.

To just rollback events, use: `webhook.rollbackRelationship('events')`
Please read the [README](https://github.com/dylanmensaert/ember-rollback-relationships/blob/master/README.md) under **API** for some detailled instructions.

Does this works for you?

**Comment by krypton9208** [comment]
Ok. but steel restore not working properly.

Before edit:
![image](https://user-images.githubusercontent.com/6137589/38811826-eb2b11a4-418a-11e8-9d05-dd571c42870c.png)
after remove 2 events only:
![image](https://user-images.githubusercontent.com/6137589/38811853-fdaf86f2-418a-11e8-9d7a-5b6576b76b76.png)

on Cancel i call:
![image](https://user-images.githubusercontent.com/6137589/38811883-0ca7883a-418b-11e8-8ca9-a3678ba3858b.png)

**Comment by dylanmensaert** [comment]
Can you show me the application `DS.Model` structure?

**Comment by dylanmensaert** [comment]
Could you also print `webhook.get('belongsToIdByName')` via console?

**Comment by krypton9208** [comment]
![image](https://user-images.githubusercontent.com/6137589/38812389-72ec917a-418c-11e8-84ad-aa198e0f2a41.png)
![image](https://user-images.githubusercontent.com/6137589/38812402-7c060d72-418c-11e8-9032-af4732447af6.png)

**Comment by dylanmensaert** [comment]
1. Did you write a `ready`, `didCreate`, `didLoad` or `didUpdate` event yourself?
2. Can you show me the **application** `DS.Model` structure?

**Comment by dylanmensaert** [comment]
belongsToIdByName[name] = belongsToId;

**Comment by dylanmensaert** [comment]
I suppose you don't have a `DS.hasMany('webhooks')` in application `DS.Model`. I will fix the code so this is not required anymore.

**Comment by dylanmensaert** [comment]
available in [v1.2.3](https://github.com/dylanmensaert/ember-rollback-relationships/releases/tag/1.2.3)

**Comment by krypton9208** [comment]
@dylanmensaert i check application model and you have right. I add "  webhook: DS.belongsTo('webhook')" to **application** model. But when i Edit webhook, i remove some events from webhook and click cancel with this actions:
```
      webhook.rollbackAttributes();
      webhook.rollbackRelationships();
```
i have this result:
![image](https://user-images.githubusercontent.com/6137589/38855771-bc7c905e-4224-11e8-9692-50ba5ee60c5b.png)

before edit
![image](https://user-images.githubusercontent.com/6137589/38855739-afcc2ba8-4224-11e8-98ea-b13e84062582.png)

So its look like hasMany wasn't restore correct....

**Comment by dylanmensaert** [comment]
Could you print `hasManyByBelongsToId[this.get('id')]` in the rollback function?

**Comment by dylanmensaert** [comment]
When calling `webhook.rollbackRelationship('events')`

**Comment by krypton9208** [comment]
![screenshot from 2018-04-17 14-11-40](https://user-images.githubusercontent.com/6137589/38868958-4b2c64ea-4249-11e8-8ef1-ab8ea0d7c634.png)

**Comment by dylanmensaert** [comment]
How do you delete your events?
Can you paste your code?

**Comment by krypton9208** [comment]
```
removeElement(elem) {
  value.removeObject(elem);
}
```

where value is array of events inserted to component (select)

**Comment by dylanmensaert** [comment]
I always use: `event.set('webhook', null);`, so in your case:

```
removeElement(elem) {
  elem.set('webhook', null);
}
```
Could you try this?

**Comment by dylanmensaert** [comment]
Could you also print the `hasManyByName` before calling any remove or rollback?

**Comment by dylanmensaert** [comment]
Could you give feedback if the proposed solution resolved your issue?
